/**
 * Autogenerated by Thrift for storage.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "GraphStorageService.h"
#include "GraphStorageService.tcc"

namespace nebula { namespace storage { namespace cpp2 {
}}} // nebula::storage::cpp2
