/**
 * Autogenerated by Thrift for meta.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "meta_metadata.h"
#include <thrift/lib/cpp2/visitation/visit_union.h>

namespace apache {
namespace thrift {
namespace detail {

template <>
struct VisitUnion<::nebula::meta::cpp2::ID> {
  template <typename F, typename T>
  void operator()(FOLLY_MAYBE_UNUSED F&& f, T&& t) const {
    using Union = std::remove_reference_t<T>;
    switch (t.getType()) {
    case Union::Type::space_id:
      return f(0, *static_cast<T&&>(t).space_id_ref());
    case Union::Type::tag_id:
      return f(1, *static_cast<T&&>(t).tag_id_ref());
    case Union::Type::edge_type:
      return f(2, *static_cast<T&&>(t).edge_type_ref());
    case Union::Type::index_id:
      return f(3, *static_cast<T&&>(t).index_id_ref());
    case Union::Type::cluster_id:
      return f(4, *static_cast<T&&>(t).cluster_id_ref());
    case Union::Type::__EMPTY__: ;
    }
  }
};
} // namespace detail
} // namespace thrift
} // namespace apache
