/**
 * Autogenerated by Thrift for meta.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once
#include "common_visitation.h"
#include "meta_for_each_field.h"
#include "meta_visit_union.h"
