/**
 * Autogenerated by Thrift for meta.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "MetaService.h"
#include "MetaService.tcc"

namespace nebula { namespace meta { namespace cpp2 {
}}} // nebula::meta::cpp2
