name: cpp_release

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  cpp-package:
    name: package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004
          - centos6
          - centos7
          - centos8
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/tagname-action
        id: tag
      - name: package
        if: contains([centos6, centos7], ${{ matrix.os }})
        run: ./package/package.sh -b ${{ steps.tag.outputs.tag }} -a ON
      - name: package abi 11
        if: contains([centos8, ubuntu1604, ubuntu1804, ubuntu2004], ${{ matrix.os }})
        run: ./package/package.sh -b ${{ steps.tag.outputs.tag }}
      - name: Get package name
        id: pkg
        run: |
          echo "::set-output name=filepath::$(find build/cpack_output -type f \( -iname \*.deb -o -iname \*.rpm \))"
      - uses: ./.github/actions/upload-assets-action
        with:
          file-path: ${{ steps.pkg.outputs.filepath }}
          tag: ${{ steps.tag.outputs.tag  }}
